name: Validar Título do PR

on:
  pull_request:
    # Roda quando o PR é aberto, editado ou recebe novos commits
    types: [opened, edited, synchronize]

jobs:
  validate-title:
    name: Validar Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checar padrão do título
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Tipos permitidos no prefixo do PR
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            release
          # Exige que o PR tenha um escopo? (ex: feat(api): ...) - false é o padrão
          requireScope: false
